TABLE_KEYWORD = "Hold'em"
PRECHECK_FOLD_POSITION_X = 385
PRECHECK_FOLD_POSITION_Y = 504
PRECHECK_CHECK_FOLD_POSITION_X = 385
PRECHECK_CHECK_FOLD_POSITION_Y = 472

# RELATIVE_FOLD_POS = 53, 67
# RELATIVE_CHECK_FOLD_POS = 53, 67
# RELATIVE_CALL_POS = 53, 67
# RELATIVE_FLAT_CALL_POS = 53, 67
# RELATIVE_FLAT_CALL_POS = 53, 67

RELATIVE_POS_CHECKBOX_FOLD = 53, 67
RELATIVE_POS_CHECKBOX_CALL = 58, 68
RELATIVE_POS_BUTTON_CHECK_OR_CALL = 73, 68
RELATIVE_POS_CHECKBOX_RAISE = 90, 68
RELATIVE_POS_BUTTON_RAISE = 90, 68

PRECHECK_FOLD = 0
PRECHECK_CALL_ANY = 0
PRECHECK_CALL_ANY_OR_CHECK = 0
PRECHECK_CALL = 0

BUTTON_FOLD = 0
BUTTON_CALL_RAISE = 0
BUTTON_PRESET_0 = 0
BUTTON_PRESET_1 = 0
BUTTON_PRESET_2 = 0
BUTTON_PRESET_3 = 0
BUTTON_BET_SIZE_DECREMENT = 0
BUTTON_BET_SIZE_INCREMENT = 0
INPUT_BET_SIZE_AMOUNT = 90, 61


# Hotkeys
HK_toggle = 'shift+p'
HK_cycle_next = 'right'
HK_cycle_prev = 'left'
HK_call = 'c'
HK_check_or_fold = 'f'
HK_fold_all = 'shift+f'
HK_RELANCE = 'r'